version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev"]
    volumes:
      - .:/app
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    working_dir: /app
    command: ["npm", "run", "dev"]
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/zappay
      - PORT=5000
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
